### ISSUE TITLE
Storage Device Rating

### ISSUE THREAD

**Issue by yinongsun** [NREL-SIIP/ExtremeSolarTexas#1]
The rating fields for all storage devices are incorrect, should be 1 under DEVICE_BASE unit system (i.e., equal to base power).

Temporary fix:
`for t in get_components(GenericBattery, sys) 
set_rating(t, 1.0) 
end`

**Comment by jd-lara** [comment]
This issue is due to a miscalculation of the reactive power limits.

**Comment by jd-lara** [comment]
closed via 05d99fb09d4d5ac170064a4b893542067dff181a
