### ISSUE TITLE
Load data magnitude

### ISSUE THREAD

**Issue by yinongsun** [NREL-SIIP/ExtremeSolarTexas#13]
This is more of a data concern instead of data issue: the system is meant to represent 2018 conditions and the actual ERCOT peak load in 2018 was 73.3 GW. However, the load in this current system is based on ACTIVSg2000, and is much lower (peak load at around 64 GW). Not sure about any specific solutions here but want to flag this for modeling work.

**Comment by jd-lara** [comment]
The peak load in the system is now 78 GW due to discrepancies in the definitions of the areas and the between the real ERCOT and the ACTIVSg2000
