### ISSUE TITLE
RT and DA data doesn't match for wind and load time series data, which should be perfect forecast

### ISSUE THREAD

**Issue by yinongsun** [NREL-SIIP/ExtremeSolarTexas#17]
Wind and load data is supposed to be perfect forecast in this dataset, but the DA value of a certain hour doesn't match either the top of hour or the mean of hour (i.e., average of 12 5-min values) of the RT data.  

An example of the load data is attached.
![image](https://user-images.githubusercontent.com/58610528/120669050-5191cb80-c44c-11eb-83b8-aed521b2852e.png)

**Comment by jd-lara** [comment]
Load data 

![image](https://user-images.githubusercontent.com/16385323/121999926-e0fb8080-cd62-11eb-90b3-a573833fb3ae.png)

**Comment by jd-lara** [comment]
wind time series 

![image](https://user-images.githubusercontent.com/16385323/122007637-01c8d380-cd6d-11eb-8e81-74c9958df00a.png)
