### ISSUE TITLE
Remove Glove Solar

### ISSUE THREAD

**Issue by kdayday** [NREL-SIIP/ExtremeSolarTexas#22]
Keeps causing problems

**Comment by jd-lara** [comment]
I don't think we should remove it, leaves an empty node. That's why it has an unavailable flag for the other studies we are making.

**Comment by kdayday** [comment]
Gotcha. It's just confusing for users, because you currently have to be "in the know" about it and make sure you check available for the PV plants, which you don't have to do for other generation types.
